# Project information
site_name: Synthstrom Deluge Community Website

# Repository
repo_url: https://github.com/seangoodvibes/DelugeDocs
edit_uri: edit/main/docs/

# Configuration
theme:
    name: material
    palette: 
        scheme: slate
        primary: black
        accent: yellow
    features:
        - content.action.edit
        - navigation.tabs     
        - navigation.expand 

# Extensions
markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation
nav:
  - Welcome: index.md
  - Documentation:
    - Introduction:
      - Introduction to the Deluge: introduction/introduction-to-the-deluge.md
      - Concepts: introduction/concepts.md
    - Getting started:
      - Firmware: getting-started/firmware.md
      - Device overview: 
          - Diagram: getting-started/device-overview/diagram.md
          - Power: getting-started/device-overview/power.md
          - Controls:
              - Knobs: getting-started/device-overview/controls/knobs.md
              - Buttons: getting-started/device-overview/controls/buttons.md
              - Pads: getting-started/device-overview/controls/pads.md
          - Ports: getting-started/device-overview/ports.md
          - Display: getting-started/device-overview/display.md
          - SD card: getting-started/device-overview/sd-card.md
          - MPE setup: getting-started/device-overview/mpe-setup.md
          - Performance: getting-started/device-overview/performance.md
  - Quick reference: quick-reference/quick-reference.md
  - External resources:
    - external-resources/external-resources.md
    - Quick links:
      - Community firmware: https://synthstromaudible.github.io/DelugeFirmware/
      - Synthstrom FAQ: https://synthstrom.com/frequently-asked-questions/
      - Display emulator: https://bfredl.github.io/delugeclient/app.html
      - File browser: https://www.fentonia.com/deluge/vuefinder/
      - Shortcuts companion: https://fheft.github.io/deluge-companion/
      - Kit Generator: https://deluge-kit-generator.vercel.app
      - Commander: https://neuma.studio/deluge-commander/
      - Delugeator: https://forums.synthstrom.com/discussion/3590/delugeator-1-0-a-win-10-kit-editor-for-deluge-released
      - Delleague: https://forums.synthstrom.com/discussion/4247/deluge-xml-fixer-and-with-set-volumes/p1?new=1
      - Kit Creator: https://synth.party/deluge-kit/
      - CC Controller: https://synth.party/cc/
  - Contributing:
    - Contributing to the documentation: contributing/contributing-to-the-docs.md
    - Language style guide: contributing/language-style-guide.md
    - Deluge style guide: contributing/deluge-style-guide.md