# Project information
site_name: Synthstrom Deluge Community Website

# Repository
repo_url: https://github.com/seangoodvibes/DelugeDocs
edit_uri: edit/main/docs/

# Configuration
theme:
    name: material
    logo: assets/logo.png  
    palette: 
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/link
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: black
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/toggle-switch-off
          name: Switch to system preference

    features:
        - content.action.edit
        - navigation.tabs   
        - navigation.footer

# Extensions
markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation
nav:
  - Welcome: index.md
  - Documentation:
    - Introduction:
      - Introduction to the Deluge: documentation/introduction/introduction-to-the-deluge.md
      - Concepts: documentation/introduction/concepts.md
    - Getting started:
      - Firmware: documentation/getting-started/firmware.md
      - Device overview: 
          - Diagram: documentation/getting-started/device-overview/diagram.md
          - Power: documentation/getting-started/device-overview/power.md
          - Controls:
              - Knobs: documentation/getting-started/device-overview/controls/knobs.md
              - Buttons: documentation/getting-started/device-overview/controls/buttons.md
              - Pads: documentation/getting-started/device-overview/controls/pads.md
          - Ports: documentation/getting-started/device-overview/ports.md
          - Display: documentation/getting-started/device-overview/display.md
          - SD card: documentation/getting-started/device-overview/sd-card.md
          - MPE setup: documentation/getting-started/device-overview/mpe-setup.md
          - Performance: documentation/getting-started/device-overview/performance.md
    - Project:
      - Settings: documentation/project/settings.md
      - Master Parameters: documentation/project/master-parameters.md
      - Track:
        - Track: documentation/project/track/track.md
        - Types: 
          - Audio: documentation/project/track/types/audio-track.md
          - Melodic Instrument:
            - Melodic Instrument: documentation/project/track/types/melodic-instrument/melodic-instrument-track.md
            - Types:
              - Synth: documentation/project/track/types/melodic-instrument/types/synth-melodic-instrument-track.md
              - MIDI: documentation/project/track/types/melodic-instrument/types/midi-melodic-instrument-track.md
              - CV: documentation/project/track/types/melodic-instrument/types/cv-melodic-instrument-track.md
          - Kit: 
            - Kit: documentation/project/track/types/kit/kit-track.md
            - Master Parameters: documentation/project/track/types/kit/kit-track-master-parameters.md
            - Drum:
              - Drum: documentation/project/track/types/kit/drum/kit-track-drum.md
              - Types:
                - Sound: documentation/project/track/types/kit/drum/types/kit-track-sound-drum.md
                - MIDI: documentation/project/track/types/kit/drum/types/kit-track-midi-drum.md
                - Gate: documentation/project/track/types/kit/drum/types/kit-track-gate-drum.md
      - Clip: 
        - Clip: documentation/project/clip/clip.md
        - Types:
          - Audio Clip: documentation/project/clip/types/audio-clip.md
          - Instrument Clip: documentation/project/clip/types/instrument-clip.md
      - Section: documentation/project/section.md
      - Playback modes: documentation/project/playback-modes.md  
      - Stem export: documentation/project/stem-export.md
    - User interface:
      - User interface: documentation/ui/user-interface.md
      - Menu:
        - Settings: documentation/ui/menu/settings.md
        - Song: 
            - Song: documentation/ui/menu/song/song.md
            - Clip settings: documentation/ui/menu/song/clip-settings.md
        - Performance: documentation/ui/menu/performance.md
        - Audio clip: documentation/ui/menu/audio-clip.md
        - Instrument clip: 
          - Sound: documentation/ui/menu/instrument-clip/sound.md
          - Kit master parameters: documentation/ui/menu/instrument-clip/kit-master-parameters.md
          - MIDI: documentation/ui/menu/instrument-clip/midi.md
          - CV: documentation/ui/menu/instrument-clip/cv.md
          - DX7 editor: documentation/ui/menu/instrument-clip/dx7-editor.md
          - Note editor: documentation/ui/menu/instrument-clip/note-editor.md
          - Note row editor: documentation/ui/menu/instrument-clip/note-row-editor.md
      - File Browser:
        - Song: documentation/ui/file-browser/song.md
        - Preset: documentation/ui/file-browser/preset.md
        - DX7: documentation/ui/file-browser/dx7.md
        - MIDI device definition file: documentation/ui/file-browser/midi-device-definition-file.md
      - Alphanumeric Keyboard: documentation/ui/alphanumeric-keyboard.md
      - Views:
        - Arranger: documentation/ui/views/arranger.md
        - Song:
          - Song: documentation/ui/views/song/song.md
          - Modes: 
            - Grid: documentation/ui/views/song/modes/grid.md
            - Row: documentation/ui/views/song/modes/row.md
        - Clip:
          - Audio clip: 
            - Audio clip: documentation/ui/views/clip/audio-clip/audio-clip.md
            - Audio clip waveform editor: documentation/ui/views/clip/audio-clip/audio-clip-waveform-editor.md
          - Instrument clip:
            - Instrument clip: documentation/ui/views/clip/instrument-clip/instrument-clip.md
            - Melodic instrument clip:
              - Melodic instrument clip: documentation/ui/views/clip/instrument-clip/melodic-instrument-clip/melodic-instrument-clip.md
              - Melodic instrument clip keyboard: documentation/ui/views/clip/instrument-clip/melodic-instrument-clip/melodic-instrument-clip-keyboard.md
            - Kit clip:
              - Kit clip: documentation/ui/views/clip/instrument-clip/kit-clip/kit-clip.md
              - Kit clip keyboard: documentation/ui/views/clip/instrument-clip/kit-clip/kit-clip-keyboard.md
              - Kit clip waveform editor: documentation/ui/views/clip/instrument-clip/kit-clip/kit-clip-waveform-editor.md
              - Kit clip lazy chopping: documentation/ui/views/clip/instrument-clip/kit-clip/kit-clip-lazy-chopping.md
            - Note editor: documentation/ui/views/clip/instrument-clip/note-editor.md
            - Note row editor: documentation/ui/views/clip/instrument-clip/note-row-editor.md
        - Automation: 
          - Parameter overview: documentation/ui/views/automation/parameter-overview.md
          - Parameter editor: documentation/ui/views/automation/parameter-editor.md
          - Note velocity editor: documentation/ui/views/automation/note-velocity-editor.md
        - Performance: 
          - Performance: documentation/ui/views/performance/performance.md
          - Value editor: documentation/ui/views/performance/value-editor.md
          - Param editor: documentation/ui/views/performance/param-editor.md
      - Rename: documentation/ui/rename.md
    - Sound engine:
      - Specs: documentation/sound-engine/specs.md
      - Synth engine:
        - Modes: 
          - Subtractive: documentation/sound-engine/synth-engine/modes/subtractive.md
          - FM: documentation/sound-engine/synth-engine/modes/fm.md
          - Ring modulation: documentation/sound-engine/synth-engine/modes/ring-modulation.md
        - Oscillator:
          - Types:
            - Basic Shapes: documentation/sound-engine/synth-engine/oscillator/types/basic-shapes.md
            - Wavetable: documentation/sound-engine/synth-engine/oscillator/types/wavetable.md
            - Sample: documentation/sound-engine/synth-engine/oscillator/types/sample.md
            - Input: documentation/sound-engine/synth-engine/oscillator/types/input.md
            - DX7: documentation/sound-engine/synth-engine/oscillator/types/dx7.md
      - Envelopes: documentation/sound-engine/envelopes.md      
      - LFOs: documentation/sound-engine/lfos.md
      - Modulation:
        - Parameters: documentation/sound-engine/modulation/parameters.md
        - Mod matrix: documentation/sound-engine/modulation/mod-matrix.md
      - Filters:
        - LPF:
          - Parameters: documentation/sound-engine/filters/lpf/lpf-parameters.md
          - Modes: documentation/sound-engine/filters/lpf/lpf-modes.md
        - HPF:
          - Parameters: documentation/sound-engine/filters/hpf/hpf-parameters.md
          - Modes: documentation/sound-engine/filters/hpf/hpf-modes.md
        - Routing: documentation/sound-engine/filters/filter-routing.md
      - FX:
        - Types:
          - EQ: documentation/sound-engine/fx/types/eq.md
          - Delay: documentation/sound-engine/fx/types/delay.md
          - Reverb: documentation/sound-engine/fx/types/reverb.md
          - Mod-fx: documentation/sound-engine/fx/types/mod-fx.md
          - Distortion: documentation/sound-engine/fx/types/distortion.md
          - Noise: documentation/sound-engine/fx/types/noise.md
    - Sequencer:
      - Specifications: documentation/sequencer/sequencer-specifications.md
      - Note:
        - Note: documentation/sequencer/note/note.md
        - Arpeggiator: documentation/sequencer/note/arpeggiator.md
      - Automation: documentation/sequencer/automation.md
    - Recording: 
      - Live looping: documentation/recording/live-looping.md
      - Audio sampling: documentation/recording/audio-sampling.md
  - External resources:
    - external-resources/external-resources.md
    - Quick links:
      - Community firmware: https://synthstromaudible.github.io/DelugeFirmware/
      - Synthstrom FAQ: https://synthstrom.com/frequently-asked-questions/
      - Display emulator: https://bfredl.github.io/delugeclient/app.html
      - File browser: https://www.fentonia.com/deluge/vuefinder/
      - Shortcuts companion: https://fheft.github.io/deluge-companion/
      - Kit Generator: https://deluge-kit-generator.vercel.app
      - Commander: https://neuma.studio/deluge-commander/
      - Delugeator: https://forums.synthstrom.com/discussion/3590/delugeator-1-0-a-win-10-kit-editor-for-deluge-released
      - Delleague: https://forums.synthstrom.com/discussion/4247/deluge-xml-fixer-and-with-set-volumes/p1?new=1
      - Kit Creator: https://synth.party/deluge-kit/
      - CC Controller: https://synth.party/cc/
  - Contributing:
    - Contributing to the documentation: contributing/contributing-to-the-docs.md
    - Language style guide: contributing/language-style-guide.md
    - Deluge style guide: contributing/deluge-style-guide.md